#!/bin/bash
#
# astroberry VAP rename script
# Author: Radek Kaczorek, rkaczorek AT gmail DOT com
# License: GPL 3.0

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo "Enter your AP name"
read -p "Name:" SSID

if [ -z "$SSID" ]; then
   echo "You must enter your AP name!"
   exit 1
fi

if [ -f /etc/hostapd/hostapd.conf ] ; then
    OLDSSID=$(grep "^ssid=" /etc/hostapd/hostapd.conf|awk -F= '{print $2}')
    if [ -z "$OLDSSID" ]; then
       echo "Error renaming AP!"
       exit 1
    else
       sed -i -e "s/ssid=$OLDSSID/ssid=$SSID/g" /etc/hostapd/hostapd.conf
       echo "AP renamed to $SSID. You need to reboot to activate changes."
       exit 0
    fi
else
    echo "No hostapd file found!"
    exit 1
fi
