#!/bin/bash
# astroberry VAP configuration script
# Author: Radek Kaczorek, rkaczorek AT gmail DOT com
# License: GPL 3.0

# remove stalled lock file
if [ -f /var/run/network/ifstate.wlan1 ] ; then
   rm -rf /var/run/network/ifstate.wlan1
fi

#add VAP
iw dev wlan0 interface add wlan1 type __ap
hostapd /etc/hostapd/hostapd.conf &

#fix for wlan0 link down
ifdown wlan0
sleep 5
ifup wlan0

#activate wlan1 dhcp and NAT configuration
service dnsmasq restart
sysctl net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -s 192.168.10.0/24 ! -d 192.168.10.0/24 -j MASQUERADE
