#!/bin/bash
#
# astroberry wlan0 configuration script
# Author: Radek Kaczorek, rkaczorek AT gmail DOT com
# License: GPL 3.0

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

echo -e "Enter your wireless network parameters\n"
read -p "Name:" SSID
read -sp "Password:" PSK
echo

if [ -z "$SSID" ] || [ -z "$PSK" ]; then
   echo "You must enter your network name and password!"
   exit 1
fi

if [ -f /etc/wpa_supplicant/wpa_supplicant.conf ] ; then
   if [ $(grep ssid /etc/wpa_supplicant/wpa_supplicant.conf | grep "$SSID" | wc -l) != 0 ]; then
       echo "Configuration for this network already exist"
       exit 1
   fi
   cp /etc/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf.bak
   cat >> /etc/wpa_supplicant/wpa_supplicant.conf << EOF
network={
ssid="$SSID"
psk="$PSK"
}
 
EOF
else
   cat > /etc/wpa_supplicant/wpa_supplicant.conf << EOF
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
 
network={
ssid="$SSID"
psk="$PSK"
}
 
EOF
fi

echo "Configuring wireless network..."

# restart wlan0 interface if new configuration is written
ifdown wlan0 > /dev/null 2>&1
sleep 3

( ifup wlan0 > /dev/null 2>&1 ) & pid=$!
( sleep 30 && kill -HUP $pid ) 2>/dev/null & watcher=$!
if wait $pid 2>/dev/null; then
   pkill -HUP -P $watcher
   echo "You are now connected to $(iwgetid -r)"
   rm -rf /etc/wpa_supplicant/wpa_supplicant.conf.bak
   exit 0
else
   echo "Error connecting to $SSID"
   if [ -f /etc/wpa_supplicant/wpa_supplicant.conf.bak ] ; then
      mv /etc/wpa_supplicant/wpa_supplicant.conf.bak /etc/wpa_supplicant/wpa_supplicant.conf
   else
      rm /etc/wpa_supplicant/wpa_supplicant.conf
   fi

   ifdown wlan0 > /dev/null 2>&1
   sleep 3

   ( ifup wlan0 > /dev/null 2>&1 ) & pid=$!
   ( sleep 30 && kill -HUP $pid ) 2>/dev/null & watcher=$!
   if wait $pid 2>/dev/null; then
      pkill -HUP -P $watcher
      echo "You are now connected to $(iwgetid -r)"
      exit 0
   fi
   echo "Error connecting to wireless network"
   exit 1
fi
