#!/bin/bash
#
# astroberry wlan0 configuration script
# Author: Radek Kaczorek, rkaczorek AT gmail DOT com
# License: GPL 3.0

if [[ $EUID -ne 0 ]]; then
   zenity --error --text="This script must be run as root" 2>/dev/null
   exit 1
fi

INPUT=$(zenity --forms --title="Configure WLAN" \
	--text="Enter information about WLAN network." \
	--separator="," \
	--add-entry="Network name" \
	--add-password="Password" 2>/dev/null)

SSID=$(awk -F, '{print $1}' <<<$INPUT)
PSK=$(awk -F, '{print $2}' <<<$INPUT)

if [ -z "$SSID" ] || [ -z "$PSK" ]; then
    zenity --error --text="\nYou must enter your network name and password." 2>/dev/null
    exit 1
fi

if [ -f /etc/wpa_supplicant/wpa_supplicant.conf ]; then
   if [ $(grep ssid /etc/wpa_supplicant/wpa_supplicant.conf | grep "$SSID" | wc -l) != 0 ]; then
       zenity --info --text="Configuration for this network already exist." 2>/dev/null
       exit 1
   fi
   cp /etc/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf.bak
   cat >> /etc/wpa_supplicant/wpa_supplicant.conf << EOF
network={
scan_ssid=1
ssid="$SSID"
psk="$PSK"
}
 
EOF
else
   cat > /etc/wpa_supplicant/wpa_supplicant.conf << EOF
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=PL

network={
scan_ssid=1
ssid="$SSID"
psk="$PSK"
}
 
EOF
fi

zenity --info --text="\nConfiguration ready.\nRestart your system to activate the wireless network" 2>/dev/null
