#!/bin/bash
#
# astroberry wlan0 configuration script
# Author: Radek Kaczorek, rkaczorek AT gmail DOT com
# License: GPL 3.0

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

echo -e "Enter your wireless network parameters\n"
read -p "Name:" SSID
read -sp "Password:" PSK
echo

if [ -z "$SSID" ] || [ -z "$PSK" ]; then
   echo "You must enter your network name and password!"
   exit 1
fi

if [ -f /etc/wpa_supplicant/wpa_supplicant.conf ] ; then
   if [ $(grep ssid /etc/wpa_supplicant/wpa_supplicant.conf | grep "$SSID" | wc -l) != 0 ]; then
       echo "Configuration for this network already exist"
       exit 1
   fi
   cp /etc/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf.bak
   cat >> /etc/wpa_supplicant/wpa_supplicant.conf << EOF
network={
scan_ssid=1
ssid="$SSID"
psk="$PSK"
}
 
EOF
else
   cat > /etc/wpa_supplicant/wpa_supplicant.conf << EOF
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=PL
 
network={
scan_ssid=1
ssid="$SSID"
psk="$PSK"
}
 
EOF
fi

echo "Configuration ready. Restart your system to activate the wireless network"

